-- 1. Create a table to store the short links
create table short_links (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  slug text unique not null,
  destination_url text not null,
  owner_email text,
  click_count int default 0
);

-- 2. Create a table to log every click (Analytics Power)
create table link_clicks (
  id bigint generated by default as identity primary key,
  link_id bigint references short_links(id),
  ip_address text,
  user_agent text,
  country text,
  device_type text,
  referer text,
  clicked_at timestamp default now()
);

-- 3. BIJOU AI LEADS TABLE - Core lead capture system
create table leads (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Lead Information
  name text not null,
  email text not null,
  phone text,
  company text,
  industry text,
  
  -- Lead Source & Context
  source text not null default 'website', -- 'hero_form', 'cal_booking', 'waitlist', 'whatsapp_cta'
  utm_source text,
  utm_medium text,
  utm_campaign text,
  referrer text,
  
  -- Lead Status & Qualification
  status text not null default 'new', -- 'new', 'contacted', 'qualified', 'customer', 'lost'
  lead_score int default 0,
  notes text,
  
  -- Privacy & Compliance
  marketing_consent boolean default false,
  pdpa_consent boolean default true,
  
  -- Analytics
  ip_address inet,
  user_agent text,
  device_type text,
  location_country text,
  location_city text,
  
  -- Email Integration
  email_sent_at timestamp with time zone,
  email_opened_at timestamp with time zone,
  email_clicked_at timestamp with time zone,
  
  -- Constraints
  constraint valid_email check (email ~* '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$'),
  constraint valid_status check (status in ('new', 'contacted', 'qualified', 'customer', 'lost')),
  constraint valid_source check (source in ('hero_form', 'cal_booking', 'waitlist', 'whatsapp_cta', 'website', 'referral'))
);

-- 4. Create indexes for performance
create index idx_leads_email on leads(email);
create index idx_leads_status on leads(status);
create index idx_leads_source on leads(source);
create index idx_leads_created_at on leads(created_at desc);
create index idx_leads_updated_at on leads(updated_at desc);

-- 5. Row Level Security (RLS) Policies
alter table leads enable row level security;

-- 6. Create a secure function to increment clicks (RPC)
create or replace function increment_click_count(row_id bigint)
returns void as $$
begin
  update short_links
  set click_count = click_count + 1
  where id = row_id;
end;
$$ language plpgsql security definer;

-- 7. Function to update lead updated_at timestamp
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

-- 8. Trigger to automatically update updated_at
create trigger update_leads_updated_at
  before update on leads
  for each row
  execute function update_updated_at_column();

-- 9. Function to calculate lead score (business logic)
create or replace function calculate_lead_score(lead_data leads)
returns int as $$
declare
  score int := 0;
begin
  -- Base score for complete profile
  if lead_data.name is not null and lead_data.email is not null then
    score := score + 10;
  end if;
  
  -- Phone number adds value
  if lead_data.phone is not null and length(lead_data.phone) > 8 then
    score := score + 15;
  end if;
  
  -- Company information valuable
  if lead_data.company is not null and length(lead_data.company) > 2 then
    score := score + 20;
  end if;
  
  -- Industry context
  if lead_data.industry is not null then
    score := score + 10;
  end if;
  
  -- Email engagement
  if lead_data.email_opened_at is not null then
    score := score + 25;
  end if;
  
  if lead_data.email_clicked_at is not null then
    score := score + 35;
  end if;
  
  -- Marketing consent shows higher intent
  if lead_data.marketing_consent = true then
    score := score + 15;
  end if;
  
  -- High-value sources
  if lead_data.source = 'cal_booking' then
    score := score + 50;  -- Booked a demo = high intent
  elsif lead_data.source = 'hero_form' then
    score := score + 30;  -- Main CTA = medium-high intent  
  elsif lead_data.source = 'whatsapp_cta' then
    score := score + 40;  -- Direct contact = high intent
  end if;
  
  return score;
end;
$$ language plpgsql;
