#!/usr/bin/env bash
# Iteratively repair the local dev scaffold from the errors the app actually
# reports.
#
# The scaffold infers columns from source patterns and inevitably misses some
# (a column only ever referenced by a helper, a PostgREST embed that needs a
# real foreign key, and so on). Rather than guess, this reads the backend log
# for PostgREST's own complaints and adds exactly what it asks for:
#
#   PGRST204  Could not find the 'slug' column of 'tenants'
#   42703     column follow_ups.scheduled_at does not exist
#   PGRST200  Could not find a relationship between 'x' and 'y'
#
# Everything it adds is `text` (or uuid/timestamptz/boolean/integer by name),
# because the app only tells us a column is MISSING, never its real type. That
# is exactly why this is a dev scaffold and not a baseline.
#
#   ./ops/local/devschema/schema-doctor.sh          one pass
#   ./ops/local/devschema/schema-doctor.sh --loop 6 repeat until quiet
set -uo pipefail

D="${DOCKER_BIN:-/mnt/c/Program Files/Docker/Docker/resources/bin/docker.exe}"
DB=bijou-local-db
BE=bijou-local-backend
PATCH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/0001_doctor_patches.sql"

coltype() {  # crude, name-based; see header
  case "$1" in
    id|*_id)              echo "uuid" ;;
    *_at|*_time|*_date)   echo "timestamptz" ;;
    is_*|has_*|allow_*|enabled|active) echo "boolean DEFAULT false" ;;
    *_count|*_days|*_minutes|*_seconds|*_order|*_step|*_priority) echo "integer" ;;
    metadata|*_json|*_data|config|settings|payload) echo "jsonb DEFAULT '{}'::jsonb" ;;
    *)                    echo "text" ;;
  esac
}

# supabase_admin, NOT postgres. The supabase/postgres image ships a
# "demote-postgres" migration, so `postgres` is no longer superuser and owns
# nothing; ALTER as postgres fails with "must be owner of table tenants".
#   $ psql -U postgres -tAc "select tableowner,count(*) from pg_tables
#                            where schemaname='"'"'public'"'"' group by 1"
#   supabase_admin|74
apply() { "$D" exec -i "$DB" psql -U supabase_admin -d postgres -v ON_ERROR_STOP=1 -q -c "$1" >/dev/null 2>&1; }

pass() {
  local added=0 log
  log="$("$D" logs --tail 400 "$BE" 2>&1 || true)"

  # PGRST204: Could not find the 'COL' column of 'TABLE'
  while IFS='|' read -r col tbl; do
    [ -z "${col:-}" ] && continue
    if apply "ALTER TABLE public.${tbl} ADD COLUMN IF NOT EXISTS ${col} $(coltype "$col");"; then
      echo "  + ${tbl}.${col}  $(coltype "$col")"
      echo "ALTER TABLE public.${tbl} ADD COLUMN IF NOT EXISTS ${col} $(coltype "$col");" >> "$PATCH"
      added=$((added+1))
    fi
  done < <(printf '%s\n' "$log" | grep -oE "Could not find the '[a-z_]+' column of '[a-z_]+'" \
            | sed -E "s/Could not find the '([a-z_]+)' column of '([a-z_]+)'/\1|\2/" | sort -u)

  # 42703: column TABLE.COL does not exist
  while IFS='|' read -r tbl col; do
    [ -z "${tbl:-}" ] && continue
    if apply "ALTER TABLE public.${tbl} ADD COLUMN IF NOT EXISTS ${col} $(coltype "$col");"; then
      echo "  + ${tbl}.${col}  $(coltype "$col")"
      echo "ALTER TABLE public.${tbl} ADD COLUMN IF NOT EXISTS ${col} $(coltype "$col");" >> "$PATCH"
      added=$((added+1))
    fi
  done < <(printf '%s\n' "$log" | grep -oE "column [a-z_]+\.[a-z_]+ does not exist" \
            | sed -E 's/column ([a-z_]+)\.([a-z_]+) does not exist/\1|\2/' | sort -u)

  # PGRST200: PostgREST embeds need a real FK, not just a matching column.
  while IFS='|' read -r child parent; do
    [ -z "${child:-}" ] && continue
    local fk="${child}_${parent%s}_id_fkey"
    apply "ALTER TABLE public.${child} ADD COLUMN IF NOT EXISTS ${parent%s}_id uuid;"
    if apply "ALTER TABLE public.${child} ADD CONSTRAINT ${fk} FOREIGN KEY (${parent%s}_id) REFERENCES public.${parent}(id) ON DELETE SET NULL;"; then
      echo "  + FK ${child}.${parent%s}_id -> ${parent}.id"
      echo "ALTER TABLE public.${child} ADD COLUMN IF NOT EXISTS ${parent%s}_id uuid;" >> "$PATCH"
      echo "ALTER TABLE public.${child} ADD CONSTRAINT ${fk} FOREIGN KEY (${parent%s}_id) REFERENCES public.${parent}(id) ON DELETE SET NULL;" >> "$PATCH"
      added=$((added+1))
    fi
  done < <(printf '%s\n' "$log" | grep -oE "relationship between '[a-z_]+' and '[a-z_]+'" \
            | sed -E "s/relationship between '([a-z_]+)' and '([a-z_]+)'/\1|\2/" | sort -u)

  echo "$added"
}

[ -f "$PATCH" ] || printf -- "-- Generated by schema-doctor.sh from the app's own PostgREST errors.\n-- Dev scaffold only. Types are guessed from column names.\n\n" > "$PATCH"

rounds="${2:-1}"; [ "${1:-}" = "--loop" ] || rounds=1
for r in $(seq 1 "$rounds"); do
  echo "── doctor pass $r ──"
  n="$(pass | tee /dev/stderr | tail -1)"
  # PostgREST caches the schema; make it reload or the next pass sees stale state.
  apply "NOTIFY pgrst, 'reload schema';"
  sleep 3
  [ "${n:-0}" = "0" ] && { echo "nothing left to add"; break; }
done
