DO $$ BEGIN ALTER TABLE public."Conversation" ADD CONSTRAINT "Conversation_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."Message" ADD CONSTRAINT "Message_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."SearchRun" ADD CONSTRAINT "SearchRun_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."User" ADD CONSTRAINT "User_email_key" UNIQUE (email); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."User" ADD CONSTRAINT "User_pkey" PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."User" ADD CONSTRAINT "User_supabaseId_key" UNIQUE ("supabaseId"); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.action_items ADD CONSTRAINT action_items_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.admin_audit_log ADD CONSTRAINT admin_audit_log_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.agent_activity ADD CONSTRAINT agent_activity_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.agent_commands ADD CONSTRAINT agent_commands_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.agent_connections ADD CONSTRAINT agent_connections_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.agent_conversations ADD CONSTRAINT agent_conversations_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.agent_messages ADD CONSTRAINT agent_messages_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.agent_runs ADD CONSTRAINT agent_runs_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.agent_status ADD CONSTRAINT agent_status_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.agent_trajectory ADD CONSTRAINT agent_trajectory_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.analytics ADD CONSTRAINT analytics_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.analytics ADD CONSTRAINT unique_tenant_date UNIQUE (tenant_id, date); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.api_keys ADD CONSTRAINT api_keys_key_hash_key UNIQUE (key_hash); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.api_keys ADD CONSTRAINT api_keys_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.audit_log ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.availability_overrides ADD CONSTRAINT availability_overrides_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.availability_overrides ADD CONSTRAINT unique_availability_override UNIQUE (tenant_id, date); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.bjx_agent_runs ADD CONSTRAINT bjx_agent_runs_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.bjx_content_drafts ADD CONSTRAINT bjx_content_drafts_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.bjx_listener_opportunities ADD CONSTRAINT bjx_listener_opportunities_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.bjx_listener_opportunities ADD CONSTRAINT bjx_listener_opportunities_source_source_url_key UNIQUE (source, source_url); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.bjx_prospect_scores ADD CONSTRAINT bjx_prospect_scores_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.bjx_prospects ADD CONSTRAINT bjx_prospects_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.bjx_prospects ADD CONSTRAINT bjx_prospects_source_source_id_key UNIQUE (source, source_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.bjx_publish_log ADD CONSTRAINT bjx_publish_log_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.bjx_review_queue ADD CONSTRAINT bjx_review_queue_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.bjx_touches ADD CONSTRAINT bjx_touches_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.blocked_numbers ADD CONSTRAINT blocked_numbers_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.blocked_numbers ADD CONSTRAINT blocked_numbers_tenant_id_customer_jid_key UNIQUE (tenant_id, customer_jid); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.business_profiles ADD CONSTRAINT business_profiles_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.business_profiles ADD CONSTRAINT unique_tenant_profile UNIQUE (tenant_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.calendar_events ADD CONSTRAINT calendar_events_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.calendar_events ADD CONSTRAINT calendar_events_user_id_google_event_id_key UNIQUE (user_id, google_event_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.call_availability ADD CONSTRAINT call_availability_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.call_availability ADD CONSTRAINT unique_availability_slot UNIQUE (tenant_id, day_of_week, start_time); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.call_bookings ADD CONSTRAINT call_bookings_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.call_logs ADD CONSTRAINT call_logs_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.call_settings ADD CONSTRAINT call_settings_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.call_settings ADD CONSTRAINT call_settings_tenant_id_key UNIQUE (tenant_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.call_types ADD CONSTRAINT call_types_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.call_types ADD CONSTRAINT unique_call_type_name UNIQUE (tenant_id, name); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.campaign_analytics ADD CONSTRAINT campaign_analytics_campaign_id_date_key UNIQUE (campaign_id, date); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.campaign_analytics ADD CONSTRAINT campaign_analytics_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.campaign_templates ADD CONSTRAINT campaign_templates_campaign_id_sequence_step_key UNIQUE (campaign_id, sequence_step); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.campaign_templates ADD CONSTRAINT campaign_templates_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.campaigns ADD CONSTRAINT campaigns_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.chats ADD CONSTRAINT chats_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.checklist_state ADD CONSTRAINT checklist_state_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.client_configs ADD CONSTRAINT client_configs_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.client_configs ADD CONSTRAINT client_configs_tenant_id_key UNIQUE (tenant_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.command_center_state ADD CONSTRAINT command_center_state_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.command_center_state ADD CONSTRAINT command_center_state_state_key_key UNIQUE (state_key); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.contact_segment_members ADD CONSTRAINT contact_segment_members_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.contact_segment_members ADD CONSTRAINT contact_segment_members_segment_id_contact_id_key UNIQUE (segment_id, contact_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.contact_segments ADD CONSTRAINT contact_segments_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.contact_segments ADD CONSTRAINT contact_segments_tenant_id_name_key UNIQUE (tenant_id, name); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.contacts ADD CONSTRAINT contacts_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.contacts ADD CONSTRAINT contacts_tenant_jid_unique UNIQUE (tenant_id, jid); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.conversation_logs ADD CONSTRAINT conversation_logs_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.conversations ADD CONSTRAINT conversations_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.conversion_events ADD CONSTRAINT conversion_events_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.customer_activity ADD CONSTRAINT customer_activity_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.customer_activity ADD CONSTRAINT customer_activity_tenant_id_customer_jid_key UNIQUE (tenant_id, customer_jid); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.customer_memory ADD CONSTRAINT customer_memory_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.customer_memory ADD CONSTRAINT customer_memory_tenant_id_chat_jid_key UNIQUE (tenant_id, chat_jid); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.daily_digests ADD CONSTRAINT daily_digests_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.daily_digests ADD CONSTRAINT daily_digests_user_id_digest_date_type_key UNIQUE (user_id, digest_date, type); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.dashboard_views ADD CONSTRAINT dashboard_views_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.data_request_deletions ADD CONSTRAINT data_request_deletions_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.decisions ADD CONSTRAINT decisions_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.departments ADD CONSTRAINT departments_name_key UNIQUE (name); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.departments ADD CONSTRAINT departments_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.device_sessions ADD CONSTRAINT device_sessions_device_id_key UNIQUE (device_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.device_sessions ADD CONSTRAINT device_sessions_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.drive_documents ADD CONSTRAINT drive_documents_google_file_id_key UNIQUE (google_file_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.drive_documents ADD CONSTRAINT drive_documents_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.email_summaries ADD CONSTRAINT email_summaries_gmail_message_id_key UNIQUE (gmail_message_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.email_summaries ADD CONSTRAINT email_summaries_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.email_templates ADD CONSTRAINT email_templates_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.email_templates ADD CONSTRAINT email_templates_tenant_type_unique UNIQUE (tenant_id, template_type); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.email_verification_tokens ADD CONSTRAINT email_verification_tokens_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.email_verification_tokens ADD CONSTRAINT email_verification_tokens_token_key UNIQUE (token); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.escalation_actions ADD CONSTRAINT escalation_actions_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.escalation_notifications ADD CONSTRAINT escalation_notifications_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.escalations ADD CONSTRAINT escalations_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.extracted_items ADD CONSTRAINT extracted_items_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.feedback ADD CONSTRAINT feedback_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.follow_ups ADD CONSTRAINT follow_ups_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.google_sheets_sync ADD CONSTRAINT google_sheets_sync_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.google_sheets_sync ADD CONSTRAINT unique_tenant_spreadsheet UNIQUE (tenant_id, spreadsheet_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.handover_agents ADD CONSTRAINT handover_agents_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.help_tickets ADD CONSTRAINT help_tickets_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.holiday_exceptions ADD CONSTRAINT holiday_exceptions_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.holiday_exceptions ADD CONSTRAINT unique_holiday_per_tenant UNIQUE (tenant_id, date); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.inbox_copilot_events ADD CONSTRAINT inbox_copilot_events_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.industry_kb_templates ADD CONSTRAINT industry_kb_templates_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.industry_kb_templates ADD CONSTRAINT industry_kb_templates_vertical_sub_vertical_language_key UNIQUE (vertical, sub_vertical, language); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.jid_mappings ADD CONSTRAINT jid_mappings_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.jid_mappings ADD CONSTRAINT uq_jid_mappings_tenant_lid UNIQUE (tenant_id, lid_jid); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.knowledge_base ADD CONSTRAINT knowledge_base_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.knowledge_bases ADD CONSTRAINT knowledge_bases_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.knowledge_chunks ADD CONSTRAINT knowledge_chunks_knowledge_base_id_chunk_index_key UNIQUE (knowledge_base_id, chunk_index); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.knowledge_chunks ADD CONSTRAINT knowledge_chunks_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.knowledge_doc_versions ADD CONSTRAINT knowledge_doc_versions_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.knowledge_documents ADD CONSTRAINT knowledge_documents_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.knowledge_sync_jobs ADD CONSTRAINT knowledge_sync_jobs_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.lead_followups ADD CONSTRAINT lead_followups_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.leads ADD CONSTRAINT leads_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.link_clicks ADD CONSTRAINT link_clicks_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.llm_usage ADD CONSTRAINT llm_usage_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.media_library ADD CONSTRAINT media_library_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.meeting_blockers ADD CONSTRAINT meeting_blockers_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.meeting_decisions ADD CONSTRAINT meeting_decisions_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.meeting_followups ADD CONSTRAINT meeting_followups_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.meeting_minutes ADD CONSTRAINT meeting_minutes_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.meetings ADD CONSTRAINT meetings_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.message_reasons ADD CONSTRAINT message_reasons_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.message_templates ADD CONSTRAINT message_templates_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.message_templates ADD CONSTRAINT unique_template_per_tenant_source UNIQUE (tenant_id, template_name, source); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.messages ADD CONSTRAINT messages_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.notification_groups ADD CONSTRAINT notification_groups_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.notification_groups ADD CONSTRAINT notification_groups_tenant_id_group_type_key UNIQUE (tenant_id, group_type); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.notification_logs ADD CONSTRAINT notification_logs_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.onboarding_progress ADD CONSTRAINT onboarding_progress_pkey PRIMARY KEY (tenant_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.onboarding_sessions ADD CONSTRAINT onboarding_sessions_pkey PRIMARY KEY (token); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.outbound_queue ADD CONSTRAINT outbound_queue_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.outreach_campaign_configs ADD CONSTRAINT outreach_campaign_configs_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.outreach_campaign_configs ADD CONSTRAINT outreach_campaign_configs_tenant_id_campaign_id_key UNIQUE (tenant_id, campaign_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.outreach_consent_log ADD CONSTRAINT outreach_consent_log_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.outreach_logs ADD CONSTRAINT outreach_logs_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.owner_commands ADD CONSTRAINT owner_commands_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.owner_devices ADD CONSTRAINT owner_devices_device_jid_key UNIQUE (device_jid); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.owner_devices ADD CONSTRAINT owner_devices_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.owner_notifications ADD CONSTRAINT owner_notifications_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.payment_transactions ADD CONSTRAINT payment_transactions_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.personas ADD CONSTRAINT personas_persona_key_key UNIQUE (persona_key); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.personas ADD CONSTRAINT personas_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.platform_admins ADD CONSTRAINT platform_admins_pkey PRIMARY KEY (user_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.projects ADD CONSTRAINT projects_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.proposals ADD CONSTRAINT proposals_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.raw_events ADD CONSTRAINT raw_events_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.response_coordinator_state ADD CONSTRAINT response_coordinator_state_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.response_coordinator_state ADD CONSTRAINT response_coordinator_state_tenant_id_chat_jid_key UNIQUE (tenant_id, chat_jid); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.scheduled_messages ADD CONSTRAINT scheduled_messages_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.shared_briefs ADD CONSTRAINT shared_briefs_pkey PRIMARY KEY (token); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.shared_context ADD CONSTRAINT shared_context_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.sheet_data ADD CONSTRAINT sheet_data_google_sheet_id_sheet_name_range_key UNIQUE (google_sheet_id, sheet_name, range); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.sheet_data ADD CONSTRAINT sheet_data_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.short_links ADD CONSTRAINT short_links_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.short_links ADD CONSTRAINT short_links_slug_key UNIQUE (slug); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.silence_rules ADD CONSTRAINT silence_rules_pkey PRIMARY KEY (tenant_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.subscription_plans ADD CONSTRAINT subscription_plans_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.subscription_plans ADD CONSTRAINT subscription_plans_plan_code_key UNIQUE (plan_code); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.system_metrics ADD CONSTRAINT system_metrics_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tasks ADD CONSTRAINT tasks_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.team_activity ADD CONSTRAINT team_activity_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.team_members ADD CONSTRAINT team_members_email_key UNIQUE (email); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.team_members ADD CONSTRAINT team_members_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_action_policy ADD CONSTRAINT tenant_action_policy_pkey PRIMARY KEY (tenant_id, tool_name); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_calendars ADD CONSTRAINT tenant_calendars_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_calendars ADD CONSTRAINT tenant_calendars_tenant_id_provider_key UNIQUE (tenant_id, provider); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_email_config ADD CONSTRAINT tenant_email_config_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_email_config ADD CONSTRAINT tenant_email_config_tenant_id_key UNIQUE (tenant_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_integrations ADD CONSTRAINT tenant_integrations_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_integrations ADD CONSTRAINT tenant_integrations_tenant_id_integration_id_key UNIQUE (tenant_id, integration_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_kb_template_instances ADD CONSTRAINT tenant_kb_template_instances_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_kb_template_instances ADD CONSTRAINT tenant_kb_template_instances_tenant_id_template_id_key UNIQUE (tenant_id, template_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_metrics ADD CONSTRAINT tenant_metrics_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_setup_progress ADD CONSTRAINT tenant_setup_progress_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_setup_progress ADD CONSTRAINT tenant_setup_progress_tenant_id_key UNIQUE (tenant_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_users ADD CONSTRAINT tenant_users_pkey1 PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_users ADD CONSTRAINT tenant_users_tenant_id_user_id_key UNIQUE (tenant_id, user_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_users_legacy ADD CONSTRAINT tenant_users_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_users_legacy ADD CONSTRAINT tenant_users_tenant_id_email_key UNIQUE (tenant_id, email); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenant_verticals ADD CONSTRAINT tenant_verticals_pkey PRIMARY KEY (tenant_id, vertical_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenants ADD CONSTRAINT tenants_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenants ADD CONSTRAINT tenants_signup_token_key UNIQUE (signup_token); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenants ADD CONSTRAINT tenants_slug_key UNIQUE (slug); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenants ADD CONSTRAINT tenants_telegram_username_key UNIQUE (telegram_username); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.tenants ADD CONSTRAINT tenants_whatsapp_number_unique UNIQUE (whatsapp_number); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.trial_notifications ADD CONSTRAINT trial_notifications_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.trial_notifications ADD CONSTRAINT unique_notification UNIQUE (tenant_id, notification_type); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.usage_tracking ADD CONSTRAINT usage_tracking_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.user_profiles ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.vertical_templates ADD CONSTRAINT vertical_templates_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.vertical_templates ADD CONSTRAINT vertical_templates_vertical_id_key UNIQUE (vertical_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.wa_learning_jobs ADD CONSTRAINT wa_learning_jobs_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.web_support_tickets ADD CONSTRAINT web_support_tickets_pkey PRIMARY KEY (id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsapp_devices ADD CONSTRAINT uq_whatsapp_devices_tenant UNIQUE (tenant_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsapp_devices ADD CONSTRAINT whatsapp_devices_pkey PRIMARY KEY (tenant_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_app_state_mutation_macs ADD CONSTRAINT whatsmeow_app_state_mutation_macs_pkey PRIMARY KEY (jid, name, version, index_mac); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_app_state_sync_keys ADD CONSTRAINT whatsmeow_app_state_sync_keys_pkey PRIMARY KEY (jid, key_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_app_state_version ADD CONSTRAINT whatsmeow_app_state_version_pkey PRIMARY KEY (jid, name); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_chat_settings ADD CONSTRAINT whatsmeow_chat_settings_pkey PRIMARY KEY (our_jid, chat_jid); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_contacts ADD CONSTRAINT whatsmeow_contacts_pkey PRIMARY KEY (our_jid, their_jid); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_device ADD CONSTRAINT whatsmeow_device_pkey PRIMARY KEY (jid); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_event_buffer ADD CONSTRAINT whatsmeow_event_buffer_pkey PRIMARY KEY (our_jid, ciphertext_hash); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_identity_keys ADD CONSTRAINT whatsmeow_identity_keys_pkey PRIMARY KEY (our_jid, their_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_lid_map ADD CONSTRAINT whatsmeow_lid_map_pkey PRIMARY KEY (lid); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_lid_map ADD CONSTRAINT whatsmeow_lid_map_pn_key UNIQUE (pn); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_message_secrets ADD CONSTRAINT whatsmeow_message_secrets_pkey PRIMARY KEY (our_jid, chat_jid, sender_jid, message_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_pre_keys ADD CONSTRAINT whatsmeow_pre_keys_pkey PRIMARY KEY (jid, key_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_privacy_tokens ADD CONSTRAINT whatsmeow_privacy_tokens_pkey PRIMARY KEY (our_jid, their_jid); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_sender_keys ADD CONSTRAINT whatsmeow_sender_keys_pkey PRIMARY KEY (our_jid, chat_id, sender_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public.whatsmeow_sessions ADD CONSTRAINT whatsmeow_sessions_pkey PRIMARY KEY (our_jid, their_id); EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;
