CREATE INDEX IF NOT EXISTS idx_action_items_deadline ON public.action_items USING btree (deadline);
CREATE INDEX IF NOT EXISTS idx_action_items_owner ON public.action_items USING btree (owner_id);
CREATE INDEX IF NOT EXISTS idx_action_items_status ON public.action_items USING btree (status);
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_action ON public.admin_audit_log USING btree (action);
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_actor_id ON public.admin_audit_log USING btree (actor_id);
CREATE INDEX IF NOT EXISTS idx_admin_audit_log_created_at ON public.admin_audit_log USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_activity_connection ON public.agent_activity USING btree (connection_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_activity_event_type ON public.agent_activity USING btree (event_type);
CREATE INDEX IF NOT EXISTS idx_agent_activity_severity ON public.agent_activity USING btree (severity);
CREATE INDEX IF NOT EXISTS idx_agent_activity_type ON public.agent_activity USING btree (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_commands_agent_status ON public.agent_commands USING btree (agent_id, status);
CREATE INDEX IF NOT EXISTS idx_agent_commands_created_at ON public.agent_commands USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_commands_issued_by ON public.agent_commands USING btree (issued_by);
CREATE INDEX IF NOT EXISTS idx_agent_connections_agent_type ON public.agent_connections USING btree (agent_type);
CREATE INDEX IF NOT EXISTS idx_agent_connections_user ON public.agent_connections USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_agent_conversations_agent_id ON public.agent_conversations USING btree (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_conversations_status ON public.agent_conversations USING btree (status);
CREATE INDEX IF NOT EXISTS idx_agent_conversations_user_id ON public.agent_conversations USING btree (user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_messages_agent_id ON public.agent_messages USING btree (agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_messages_conversation_created ON public.agent_messages USING btree (conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_agent_runs_created ON public.agent_runs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_status_connection ON public.agent_status USING btree (connection_id, checked_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_trajectory_tenant_chat ON public.agent_trajectory USING btree (tenant_id, chat_jid, ts);
CREATE INDEX IF NOT EXISTS idx_analytics_date ON public.analytics USING btree (date DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_tenant ON public.analytics USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_api_keys_tenant ON public.api_keys USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_action ON public.audit_log USING btree (action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_actor ON public.audit_log USING btree (actor_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_created ON public.audit_log USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_log_target ON public.audit_log USING btree (target_type, target_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_availability_overrides_date ON public.availability_overrides USING btree (date);
CREATE INDEX IF NOT EXISTS idx_availability_overrides_tenant_id ON public.availability_overrides USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_bjx_agent_runs_agent ON public.bjx_agent_runs USING btree (agent_name);
CREATE INDEX IF NOT EXISTS idx_bjx_agent_runs_created ON public.bjx_agent_runs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bjx_agent_runs_status ON public.bjx_agent_runs USING btree (status);
CREATE INDEX IF NOT EXISTS idx_bjx_content_drafts_kind ON public.bjx_content_drafts USING btree (kind);
CREATE INDEX IF NOT EXISTS idx_bjx_content_drafts_pillar ON public.bjx_content_drafts USING btree (pillar_id);
CREATE INDEX IF NOT EXISTS idx_bjx_content_drafts_scheduled ON public.bjx_content_drafts USING btree (scheduled_for);
CREATE INDEX IF NOT EXISTS idx_bjx_content_drafts_status ON public.bjx_content_drafts USING btree (status);
CREATE INDEX IF NOT EXISTS idx_agent_listener_match ON public.bjx_listener_opportunities USING btree (match_score DESC);
CREATE INDEX IF NOT EXISTS idx_agent_listener_status ON public.bjx_listener_opportunities USING btree (status);
CREATE INDEX IF NOT EXISTS idx_bjx_prospect_scores_fit ON public.bjx_prospect_scores USING btree (fit_score DESC);
CREATE INDEX IF NOT EXISTS idx_bjx_prospect_scores_prospect ON public.bjx_prospect_scores USING btree (prospect_id);
CREATE INDEX IF NOT EXISTS idx_bjx_prospects_area ON public.bjx_prospects USING btree (area);
CREATE INDEX IF NOT EXISTS idx_bjx_prospects_created ON public.bjx_prospects USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bjx_prospects_status ON public.bjx_prospects USING btree (status);
CREATE INDEX IF NOT EXISTS idx_bjx_prospects_vertical ON public.bjx_prospects USING btree (vertical);
CREATE INDEX IF NOT EXISTS idx_bjx_publish_log_draft ON public.bjx_publish_log USING btree (content_draft_id);
CREATE INDEX IF NOT EXISTS idx_bjx_publish_log_status ON public.bjx_publish_log USING btree (status);
CREATE INDEX IF NOT EXISTS idx_bjx_review_queue_expires ON public.bjx_review_queue USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_bjx_review_queue_priority ON public.bjx_review_queue USING btree (priority DESC, created_at);
CREATE INDEX IF NOT EXISTS idx_bjx_review_queue_status ON public.bjx_review_queue USING btree (status);
CREATE INDEX IF NOT EXISTS idx_bjx_touches_channel ON public.bjx_touches USING btree (channel);
CREATE INDEX IF NOT EXISTS idx_bjx_touches_prospect ON public.bjx_touches USING btree (prospect_id);
CREATE INDEX IF NOT EXISTS idx_bjx_touches_sent_at ON public.bjx_touches USING btree (sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_blocked_active ON public.blocked_numbers USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_blocked_expires ON public.blocked_numbers USING btree (expires_at) WHERE (expires_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_blocked_jid ON public.blocked_numbers USING btree (customer_jid) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_blocked_tenant ON public.blocked_numbers USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_calendar_events_start_time ON public.calendar_events USING btree (start_time);
CREATE INDEX IF NOT EXISTS idx_calendar_events_user_id ON public.calendar_events USING btree (user_id, start_time);
CREATE INDEX IF NOT EXISTS idx_call_availability_active ON public.call_availability USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_call_availability_day ON public.call_availability USING btree (day_of_week);
CREATE INDEX IF NOT EXISTS idx_call_availability_tenant_id ON public.call_availability USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_call_bookings_customer_jid ON public.call_bookings USING btree (customer_jid);
CREATE INDEX IF NOT EXISTS idx_call_bookings_scheduled_date ON public.call_bookings USING btree (scheduled_date);
CREATE INDEX IF NOT EXISTS idx_call_bookings_scheduled_time ON public.call_bookings USING btree (scheduled_time);
CREATE INDEX IF NOT EXISTS idx_call_bookings_status ON public.call_bookings USING btree (status);
CREATE INDEX IF NOT EXISTS idx_call_bookings_tenant_date ON public.call_bookings USING btree (tenant_id, scheduled_date);
CREATE INDEX IF NOT EXISTS idx_call_bookings_tenant_id ON public.call_bookings USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_call_types_active ON public.call_types USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_call_types_tenant_id ON public.call_types USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_campaign_analytics_date ON public.campaign_analytics USING btree (campaign_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_campaigns_scheduled_start ON public.campaigns USING btree (scheduled_start_at) WHERE (status = 'scheduled'::text);
CREATE INDEX IF NOT EXISTS idx_campaigns_tenant_status ON public.campaigns USING btree (tenant_id, status) WHERE (status = ANY (ARRAY['scheduled'::text, 'running'::text]));
CREATE INDEX IF NOT EXISTS idx_chats_jid ON public.chats USING btree (jid);
CREATE INDEX IF NOT EXISTS idx_chats_last_message ON public.chats USING btree (last_message_at DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS idx_chats_tenant_id ON public.chats USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_segment_members_contact ON public.contact_segment_members USING btree (contact_id);
CREATE INDEX IF NOT EXISTS idx_segment_members_segment ON public.contact_segment_members USING btree (segment_id);
CREATE INDEX IF NOT EXISTS idx_contact_segments_tenant ON public.contact_segments USING btree (tenant_id, segment_type);
CREATE INDEX IF NOT EXISTS idx_contacts_campaign_config ON public.contacts USING btree (campaign_config_id) WHERE (campaign_config_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_contacts_do_not_contact ON public.contacts USING btree (tenant_id, do_not_contact) WHERE (do_not_contact = true);
CREATE INDEX IF NOT EXISTS idx_contacts_industry_type ON public.contacts USING btree (tenant_id, industry_type) WHERE (industry_type IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_contacts_interest_score ON public.contacts USING btree (tenant_id, interest_score DESC) WHERE (interest_score > 0);
CREATE INDEX IF NOT EXISTS idx_contacts_outreach ON public.contacts USING btree (tenant_id, last_outreach_at) WHERE (last_outreach_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_contacts_tenant_last_msg ON public.contacts USING btree (tenant_id, last_message_at DESC);
CREATE INDEX IF NOT EXISTS idx_contacts_tenant_status ON public.contacts USING btree (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_contacts_tenant_tag ON public.contacts USING btree (tenant_id, tag);
CREATE INDEX IF NOT EXISTS idx_conversation_logs_chat ON public.conversation_logs USING btree (chat_jid);
CREATE INDEX IF NOT EXISTS idx_conversation_logs_created_at ON public.conversation_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversation_logs_event_type ON public.conversation_logs USING btree (event_type);
CREATE INDEX IF NOT EXISTS idx_conversation_logs_failures ON public.conversation_logs USING btree (tenant_id, success) WHERE (success = false);
CREATE INDEX IF NOT EXISTS idx_conversation_logs_tenant ON public.conversation_logs USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_conversations_chat_jid ON public.conversations USING btree (chat_jid);
CREATE INDEX IF NOT EXISTS idx_conversations_contact_name ON public.conversations USING btree (contact_name);
CREATE INDEX IF NOT EXISTS idx_conversations_customer ON public.conversations USING btree (customer_jid);
CREATE INDEX IF NOT EXISTS idx_conversations_tenant ON public.conversations USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_conversations_tenant_chat ON public.conversations USING btree (tenant_id, chat_jid);
CREATE INDEX IF NOT EXISTS idx_conversations_timestamp ON public.conversations USING btree ("timestamp" DESC);
CREATE INDEX IF NOT EXISTS idx_conversion_events_date ON public.conversion_events USING btree (converted_at);
CREATE INDEX IF NOT EXISTS idx_conversion_events_tenant ON public.conversion_events USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_conversion_events_type ON public.conversion_events USING btree (event_type);
CREATE INDEX IF NOT EXISTS idx_customer_activity_last_message ON public.customer_activity USING btree (last_message_at);
CREATE INDEX IF NOT EXISTS idx_customer_activity_tenant ON public.customer_activity USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_dashboard_views_created_by ON public.dashboard_views USING btree (created_by);
CREATE INDEX IF NOT EXISTS idx_dashboard_views_dept_visibility ON public.dashboard_views USING btree (department_id, visibility);
CREATE INDEX IF NOT EXISTS idx_dashboard_views_pinned ON public.dashboard_views USING btree (pinned) WHERE (pinned = true);
CREATE UNIQUE INDEX IF NOT EXISTS idx_data_request_deletions_phone ON public.data_request_deletions USING btree (phone_normalized);
CREATE INDEX IF NOT EXISTS idx_data_request_deletions_status_grace ON public.data_request_deletions USING btree (status, grace_until);
CREATE INDEX IF NOT EXISTS idx_departments_parent ON public.departments USING btree (parent_id);
CREATE INDEX IF NOT EXISTS idx_device_sessions_device_id ON public.device_sessions USING btree (device_id);
CREATE INDEX IF NOT EXISTS idx_device_sessions_status ON public.device_sessions USING btree (status);
CREATE INDEX IF NOT EXISTS idx_device_sessions_tenant_id ON public.device_sessions USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_drive_documents_mime_type ON public.drive_documents USING btree (mime_type);
CREATE INDEX IF NOT EXISTS idx_drive_documents_owner_user_id ON public.drive_documents USING btree (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_email_summaries_ai_urgency ON public.email_summaries USING btree (ai_urgency);
CREATE INDEX IF NOT EXISTS idx_email_summaries_thread_id ON public.email_summaries USING btree (gmail_thread_id);
CREATE INDEX IF NOT EXISTS idx_email_summaries_user_id ON public.email_summaries USING btree (user_id, received_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_templates_tenant_type ON public.email_templates USING btree (tenant_id, template_type) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_email_tokens_expires ON public.email_verification_tokens USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_email_tokens_tenant ON public.email_verification_tokens USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_escalation_actions_created ON public.escalation_actions USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_escalation_actions_escalation ON public.escalation_actions USING btree (escalation_id);
CREATE INDEX IF NOT EXISTS idx_escalation_actions_type ON public.escalation_actions USING btree (action_type);
CREATE INDEX IF NOT EXISTS idx_escalation_notifications_created ON public.escalation_notifications USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_escalation_notifications_escalation ON public.escalation_notifications USING btree (escalation_id);
CREATE INDEX IF NOT EXISTS idx_escalation_notifications_status ON public.escalation_notifications USING btree (status);
CREATE INDEX IF NOT EXISTS idx_escalation_notifications_tenant ON public.escalation_notifications USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_escalations_agent_status ON public.escalations USING btree (assigned_agent_id, status) WHERE (assigned_agent_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_escalations_assigned_agent ON public.escalations USING btree (assigned_agent_id);
CREATE INDEX IF NOT EXISTS idx_escalations_chat ON public.escalations USING btree (chat_jid);
CREATE INDEX IF NOT EXISTS idx_escalations_priority ON public.escalations USING btree (priority, created_at);
CREATE INDEX IF NOT EXISTS idx_escalations_reason_type ON public.escalations USING btree (reason_type);
CREATE INDEX IF NOT EXISTS idx_escalations_sla ON public.escalations USING btree (sla_deadline) WHERE (status = ANY (ARRAY['pending'::text, 'claimed'::text]));
CREATE INDEX IF NOT EXISTS idx_escalations_status ON public.escalations USING btree (status);
CREATE INDEX IF NOT EXISTS idx_escalations_status_sla ON public.escalations USING btree (status, sla_deadline) WHERE ((status = ANY (ARRAY['pending'::text, 'in_progress'::text])) AND (sla_deadline IS NOT NULL));
CREATE INDEX IF NOT EXISTS idx_escalations_tenant ON public.escalations USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_escalations_tenant_chat ON public.escalations USING btree (tenant_id, chat_jid);
CREATE INDEX IF NOT EXISTS idx_escalations_tenant_status ON public.escalations USING btree (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_escalations_timeout_candidates ON public.escalations USING btree (tenant_id, status, escalation_triggered_at) WHERE (status = ANY (ARRAY['pending'::text, 'in_progress'::text]));
CREATE INDEX IF NOT EXISTS idx_escalations_updated_at ON public.escalations USING btree (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_escalations_warning_candidates ON public.escalations USING btree (tenant_id, status, warning_sent, escalation_triggered_at) WHERE ((status = ANY (ARRAY['pending'::text, 'in_progress'::text])) AND (warning_sent = false));
CREATE INDEX IF NOT EXISTS idx_extracted_items_status ON public.extracted_items USING btree (status);
CREATE INDEX IF NOT EXISTS idx_extracted_items_type ON public.extracted_items USING btree (item_type);
CREATE INDEX IF NOT EXISTS idx_feedback_created ON public.feedback USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedback_customer ON public.feedback USING btree (customer_jid);
CREATE INDEX IF NOT EXISTS idx_feedback_follow_up ON public.feedback USING btree (follow_up_needed) WHERE (follow_up_needed = true);
CREATE INDEX IF NOT EXISTS idx_feedback_rating ON public.feedback USING btree (rating);
CREATE INDEX IF NOT EXISTS idx_feedback_sentiment ON public.feedback USING btree (sentiment);
CREATE INDEX IF NOT EXISTS idx_feedback_tenant ON public.feedback USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_follow_ups_chat ON public.follow_ups USING btree (chat_jid, status);
CREATE INDEX IF NOT EXISTS idx_follow_ups_pending ON public.follow_ups USING btree (status, scheduled_at) WHERE (status = 'pending'::text);
CREATE INDEX IF NOT EXISTS idx_follow_ups_scheduled ON public.follow_ups USING btree (scheduled_at) WHERE (status = 'pending'::text);
CREATE INDEX IF NOT EXISTS idx_follow_ups_status ON public.follow_ups USING btree (status, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_follow_ups_tenant ON public.follow_ups USING btree (tenant_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_follow_ups_unique_pending ON public.follow_ups USING btree (tenant_id, chat_jid) WHERE (status = 'pending'::text);
CREATE INDEX IF NOT EXISTS idx_sheets_sync_enabled ON public.google_sheets_sync USING btree (sync_enabled);
CREATE INDEX IF NOT EXISTS idx_sheets_sync_tenant ON public.google_sheets_sync USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_handover_agents_active ON public.handover_agents USING btree (tenant_id, is_active);
CREATE INDEX IF NOT EXISTS idx_handover_agents_is_active ON public.handover_agents USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_handover_agents_priority ON public.handover_agents USING btree (priority_level);
CREATE INDEX IF NOT EXISTS idx_handover_agents_tenant_id ON public.handover_agents USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_help_tickets_group_jid ON public.help_tickets USING btree (group_jid, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_help_tickets_tenant_status ON public.help_tickets USING btree (tenant_id, status, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_help_ticket_number ON public.help_tickets USING btree (tenant_id, ticket_number);
CREATE INDEX IF NOT EXISTS idx_holiday_exceptions_date ON public.holiday_exceptions USING btree (date);
CREATE INDEX IF NOT EXISTS idx_holiday_exceptions_tenant_id ON public.holiday_exceptions USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_inbox_copilot_events_event ON public.inbox_copilot_events USING btree (event_id);
CREATE INDEX IF NOT EXISTS idx_inbox_copilot_events_tenant ON public.inbox_copilot_events USING btree (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_jid_mappings_phone_jid ON public.jid_mappings USING btree (tenant_id, phone_jid);
CREATE INDEX IF NOT EXISTS idx_knowledge_base_tenant_id ON public.knowledge_base USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_content_fts ON public.knowledge_base USING gin (to_tsvector('english'::regconfig, content));
CREATE INDEX IF NOT EXISTS idx_knowledge_created ON public.knowledge_base USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_knowledge_keywords ON public.knowledge_base USING gin (keywords);
CREATE INDEX IF NOT EXISTS idx_knowledge_status ON public.knowledge_base USING btree (processing_status);
CREATE INDEX IF NOT EXISTS idx_knowledge_topics ON public.knowledge_base USING gin (topics);
CREATE INDEX IF NOT EXISTS idx_knowledge_active ON public.knowledge_bases USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_knowledge_bases_tenant ON public.knowledge_bases USING btree (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_knowledge_category ON public.knowledge_bases USING btree (category);
CREATE INDEX IF NOT EXISTS idx_knowledge_tenant ON public.knowledge_bases USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_chunks_embedding ON public.knowledge_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists='100');
CREATE INDEX IF NOT EXISTS idx_knowledge_chunks_kb ON public.knowledge_chunks USING btree (knowledge_base_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_chunks_tenant ON public.knowledge_chunks USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_kdv_document_id ON public.knowledge_doc_versions USING btree (document_id, version_number DESC);
CREATE INDEX IF NOT EXISTS idx_kdv_tenant_id ON public.knowledge_doc_versions USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_docs_status ON public.knowledge_documents USING btree (status);
CREATE INDEX IF NOT EXISTS idx_knowledge_docs_tenant_id ON public.knowledge_documents USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_docs_uploaded_at ON public.knowledge_documents USING btree (tenant_id, uploaded_at DESC);
CREATE INDEX IF NOT EXISTS idx_knowledge_sync_jobs_kb ON public.knowledge_sync_jobs USING btree (knowledge_base_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_sync_jobs_status ON public.knowledge_sync_jobs USING btree (status);
CREATE INDEX IF NOT EXISTS idx_knowledge_sync_jobs_tenant ON public.knowledge_sync_jobs USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_lead_followups_next ON public.lead_followups USING btree (next_followup_at);
CREATE INDEX IF NOT EXISTS idx_lead_followups_tenant ON public.lead_followups USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON public.leads USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_email ON public.leads USING btree (email);
CREATE INDEX IF NOT EXISTS idx_leads_lead_score ON public.leads USING btree (lead_score DESC);
CREATE INDEX IF NOT EXISTS idx_leads_source ON public.leads USING btree (source);
CREATE INDEX IF NOT EXISTS idx_leads_status ON public.leads USING btree (status);
CREATE INDEX IF NOT EXISTS idx_leads_updated_at ON public.leads USING btree (updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_media_tenant ON public.media_library USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_meeting_blockers_status ON public.meeting_blockers USING btree (status);
CREATE INDEX IF NOT EXISTS idx_meetings_date ON public.meetings USING btree (meeting_date);
CREATE INDEX IF NOT EXISTS idx_message_reasons_chat ON public.message_reasons USING btree (tenant_id, chat_jid, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_message_reasons_lookup ON public.message_reasons USING btree (tenant_id, message_id);
CREATE INDEX IF NOT EXISTS idx_message_templates_active ON public.message_templates USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_message_templates_tenant ON public.message_templates USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_templates_trigger_mode ON public.message_templates USING btree (tenant_id, trigger_mode);
CREATE INDEX IF NOT EXISTS idx_messages_chat_jid ON public.messages USING btree (chat_jid);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_key ON public.messages USING btree (conversation_key) WHERE (conversation_key IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_messages_customer_name ON public.messages USING btree (customer_name);
CREATE INDEX IF NOT EXISTS idx_messages_customer_phone ON public.messages USING btree (customer_phone);
CREATE INDEX IF NOT EXISTS idx_messages_device_jid ON public.messages USING btree (device_jid) WHERE (device_jid IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_messages_system_event ON public.messages USING btree (tenant_id, is_system_event) WHERE (is_system_event = false);
CREATE INDEX IF NOT EXISTS idx_messages_tenant_chat ON public.messages USING btree (tenant_id, chat_jid);
CREATE INDEX IF NOT EXISTS idx_messages_tenant_id ON public.messages USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_messages_tenant_id_created ON public.messages USING btree (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_timestamp ON public.messages USING btree ("timestamp" DESC);
CREATE INDEX IF NOT EXISTS idx_notification_groups_group_type ON public.notification_groups USING btree (group_type);
CREATE INDEX IF NOT EXISTS idx_notification_groups_tenant_id ON public.notification_groups USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_notification_logs_customer_jid ON public.notification_logs USING btree (customer_jid);
CREATE INDEX IF NOT EXISTS idx_notification_logs_sent_at ON public.notification_logs USING btree (sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_notification_logs_tenant_id ON public.notification_logs USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications USING btree (user_id, read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_onboarding_progress_current_step ON public.onboarding_progress USING btree (current_step);
CREATE INDEX IF NOT EXISTS idx_onboarding_created ON public.onboarding_sessions USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_onboarding_email ON public.onboarding_sessions USING btree (email);
CREATE INDEX IF NOT EXISTS idx_onboarding_expires ON public.onboarding_sessions USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_onboarding_status ON public.onboarding_sessions USING btree (status);
CREATE INDEX IF NOT EXISTS idx_onboarding_tenant ON public.onboarding_sessions USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_token ON public.onboarding_sessions USING btree (token) WHERE (status <> 'completed'::text);
CREATE INDEX IF NOT EXISTS idx_outbound_queue_campaign ON public.outbound_queue USING btree (campaign_id, status);
CREATE INDEX IF NOT EXISTS idx_outbound_queue_contact ON public.outbound_queue USING btree (contact_id, campaign_id) WHERE (replied_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_outbound_queue_daily_check ON public.outbound_queue USING btree (tenant_id, sent_at);
CREATE INDEX IF NOT EXISTS idx_outbound_queue_pending ON public.outbound_queue USING btree (tenant_id, status, scheduled_at) WHERE (status = ANY (ARRAY['pending'::text, 'scheduled'::text]));
CREATE INDEX IF NOT EXISTS idx_occ_active ON public.outreach_campaign_configs USING btree (tenant_id, is_active) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_occ_industry ON public.outreach_campaign_configs USING btree (industry_type);
CREATE INDEX IF NOT EXISTS idx_occ_tenant ON public.outreach_campaign_configs USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_outreach_consent_active ON public.outreach_consent_log USING btree (tenant_id, contact_id) WHERE (revoked_at IS NULL);
CREATE INDEX IF NOT EXISTS idx_outreach_consent_contact ON public.outreach_consent_log USING btree (tenant_id, contact_id, revoked_at);
CREATE INDEX IF NOT EXISTS idx_outreach_logs_tenant ON public.outreach_logs USING btree (tenant_id, log_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_owner_commands_created ON public.owner_commands USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_owner_commands_owner ON public.owner_commands USING btree (owner_jid);
CREATE INDEX IF NOT EXISTS idx_owner_commands_tenant ON public.owner_commands USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_owner_commands_type ON public.owner_commands USING btree (command_type);
CREATE INDEX IF NOT EXISTS idx_owner_notifications_chat ON public.owner_notifications USING btree (chat_jid);
CREATE INDEX IF NOT EXISTS idx_owner_notifications_sent_at ON public.owner_notifications USING btree (sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_owner_notifications_tenant ON public.owner_notifications USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON public.payment_transactions USING btree (status);
CREATE INDEX IF NOT EXISTS idx_payments_stripe_intent ON public.payment_transactions USING btree (stripe_payment_intent_id);
CREATE INDEX IF NOT EXISTS idx_payments_tenant ON public.payment_transactions USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_personas_active ON public.personas USING btree (is_active) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_personas_tenant ON public.personas USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_projects_department_id ON public.projects USING btree (department_id);
CREATE INDEX IF NOT EXISTS idx_projects_owner_id ON public.projects USING btree (owner_id);
CREATE INDEX IF NOT EXISTS idx_projects_status ON public.projects USING btree (status);
CREATE INDEX IF NOT EXISTS idx_proposals_status ON public.proposals USING btree (status);
CREATE INDEX IF NOT EXISTS idx_raw_events_processed ON public.raw_events USING btree (processed);
CREATE INDEX IF NOT EXISTS idx_raw_events_source ON public.raw_events USING btree (source);
CREATE INDEX IF NOT EXISTS idx_response_coord_activity ON public.response_coordinator_state USING btree (last_activity_at);
CREATE INDEX IF NOT EXISTS idx_response_coord_tenant ON public.response_coordinator_state USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_messages_active_nextrun ON public.scheduled_messages USING btree (is_active, next_run_at) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_scheduled_messages_next_run ON public.scheduled_messages USING btree (next_run_at) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_scheduled_messages_status_time ON public.scheduled_messages USING btree (status, scheduled_time) WHERE (status = 'pending'::text);
CREATE INDEX IF NOT EXISTS idx_scheduled_messages_tenant ON public.scheduled_messages USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_shared_briefs_created_at ON public.shared_briefs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_shared_context_lookup ON public.shared_context USING btree (tenant_id, customer_phone, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_shared_context_thread ON public.shared_context USING btree (tenant_id, thread_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sheet_data_sheet_id ON public.sheet_data USING btree (google_sheet_id);
CREATE INDEX IF NOT EXISTS idx_system_metrics_name_time ON public.system_metrics USING btree (metric_name, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to ON public.tasks USING btree (assigned_to);
CREATE INDEX IF NOT EXISTS idx_tasks_project_id ON public.tasks USING btree (project_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON public.tasks USING btree (status);
CREATE INDEX IF NOT EXISTS idx_tenant_calendars_tenant_id ON public.tenant_calendars USING btree (tenant_id) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_tenant_email_config_tenant_id ON public.tenant_email_config USING btree (tenant_id) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_tenant_integrations_tenant_id ON public.tenant_integrations USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_kb_instances_tenant ON public.tenant_kb_template_instances USING btree (tenant_id, is_complete);
CREATE INDEX IF NOT EXISTS idx_tenant_metrics_name ON public.tenant_metrics USING btree (metric_name);
CREATE INDEX IF NOT EXISTS idx_tenant_metrics_tenant_time ON public.tenant_metrics USING btree (tenant_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_tenant_users_tenant_id ON public.tenant_users USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_users_user_id ON public.tenant_users USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_tenant_users_email ON public.tenant_users_legacy USING btree (email);
CREATE INDEX IF NOT EXISTS idx_tenant_users_main_contact ON public.tenant_users_legacy USING btree (tenant_id, is_main_contact) WHERE (is_main_contact = true);
CREATE INDEX IF NOT EXISTS idx_tenant_verticals_tenant_id ON public.tenant_verticals USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenants_auto_reply ON public.tenants USING btree (auto_reply_enabled) WHERE (auto_reply_enabled = true);
CREATE INDEX IF NOT EXISTS idx_tenants_device_id ON public.tenants USING btree (device_id);
CREATE INDEX IF NOT EXISTS idx_tenants_email ON public.tenants USING btree (email);
CREATE INDEX IF NOT EXISTS idx_tenants_email_token ON public.tenants USING btree (email_verification_token);
CREATE INDEX IF NOT EXISTS idx_tenants_handover_primary ON public.tenants USING btree (handover_primary) WHERE (handover_primary IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_tenants_status ON public.tenants USING btree (status);
CREATE INDEX IF NOT EXISTS idx_tenants_stripe_customer_id ON public.tenants USING btree (stripe_customer_id);
CREATE INDEX IF NOT EXISTS idx_tenants_stripe_subscription ON public.tenants USING btree (stripe_subscription_id);
CREATE INDEX IF NOT EXISTS idx_tenants_testing_mode ON public.tenants USING btree (testing_mode) WHERE (testing_mode = true);
CREATE INDEX IF NOT EXISTS idx_tenants_tier ON public.tenants USING btree (subscription_tier);
CREATE INDEX IF NOT EXISTS idx_tenants_whatsapp_jid ON public.tenants USING btree (whatsapp_jid);
CREATE INDEX IF NOT EXISTS idx_trial_notif_tenant ON public.trial_notifications USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_trial_notif_type ON public.trial_notifications USING btree (notification_type);
CREATE INDEX IF NOT EXISTS idx_usage_created ON public.usage_tracking USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_usage_customer ON public.usage_tracking USING btree (customer_jid);
CREATE INDEX IF NOT EXISTS idx_usage_tenant_date ON public.usage_tracking USING btree (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_profiles_dept ON public.user_profiles USING btree (department_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_email ON public.user_profiles USING btree (email);
CREATE INDEX IF NOT EXISTS idx_user_profiles_manager ON public.user_profiles USING btree (manager_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_role ON public.user_profiles USING btree (role);
CREATE INDEX IF NOT EXISTS idx_web_support_tickets_email ON public.web_support_tickets USING btree (submitter_email, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_web_support_tickets_status ON public.web_support_tickets USING btree (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_whatsapp_devices_device_id ON public.whatsapp_devices USING btree (device_id);
CREATE INDEX IF NOT EXISTS idx_whatsapp_devices_tenant ON public.whatsapp_devices USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_whatsapp_devices_whatsapp_jid ON public.whatsapp_devices USING btree (whatsapp_jid);
