#!/usr/bin/env bash
# Mint the local anon / service_role JWTs and write ops/local/.env.local.
#
# These cannot be hardcoded in docker-compose.local.yml for two reasons:
#   1. PostgREST validates them against PGRST_JWT_SECRET, so they have to be
#      real HS256 tokens signed with the local secret — a dummy string fails.
#   2. Any literal starting "eyJ" trips the repo's pre-commit secret guard,
#      and rightly so; a committed token-shaped string is exactly what that
#      hook exists to stop.
#
# Idempotent: re-running regenerates the file. Safe to call on every `up`.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/.env.local"

JWT_SECRET="${LOCAL_JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters}"
DB_PASSWORD="${LOCAL_DB_PASSWORD:-postgres}"
# 2035-ish. Local tokens should not expire mid-debugging-session.
EXP="2065360000"
IAT="1750000000"

b64url() { openssl base64 -A | tr '+/' '-_' | tr -d '='; }

mint() {
  local role="$1"
  local header payload signing_input sig
  header=$(printf '{"alg":"HS256","typ":"JWT"}' | b64url)
  payload=$(printf '{"role":"%s","iss":"supabase-local","iat":%s,"exp":%s}' \
              "$role" "$IAT" "$EXP" | b64url)
  signing_input="${header}.${payload}"
  sig=$(printf '%s' "$signing_input" \
        | openssl dgst -binary -sha256 -hmac "$JWT_SECRET" \
        | b64url)
  printf '%s.%s' "$signing_input" "$sig"
}

command -v openssl >/dev/null 2>&1 || {
  echo "FATAL: openssl not found; needed to sign the local JWTs." >&2
  exit 1
}

ANON_KEY="$(mint anon)"
SERVICE_KEY="$(mint service_role)"

cat > "$OUT" <<EOF
# GENERATED by ops/local/gen-local-keys.sh — do not commit, do not reuse.
# These are local-development tokens signed with a publicly-known secret.
# They grant nothing outside this machine's docker network.
LOCAL_JWT_SECRET=$JWT_SECRET
LOCAL_DB_PASSWORD=$DB_PASSWORD
SUPABASE_URL=http://supabase-gateway:8000
SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_KEY=$SERVICE_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY
SUPABASE_KEY=$SERVICE_KEY
EOF

chmod 600 "$OUT"
echo "wrote $OUT (anon + service_role JWTs, signed with the local secret)"
